format = """
[](#264653)\
$os\
$username\
[](bg:#2a9d8f fg:#264653)\
$directory\
[](fg:#2a9d8f bg:#f4a261)\
$git_branch\
$git_status\
[](fg:#f4a261 bg:#e76f51)\
$time\
[ ](fg:#e76f51)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#ffffff bg:#264653"
style_root = "bg:#264653"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#264653"
disabled = true # Disabled by default

[directory]
style = "fg:#000000 bg:#2a9d8f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "fg:#000000 bg:#f4a261"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#000000 bg:#f4a261"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#000000 bg:#e76f51"
format = '[  $time ]($style)'
